name: Production deploy
on:
  release:
    tags:
      - v*

jobs:
  prod-deploy:
    name: Production deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        if: github.event.action == 'published'
        uses: actions/checkout@master
        
      - name: Run Tests
        run: ls
